export const mockDataAvilable = [
    { id: 1, taName: 'John Doe', username: 'johndoe', availability: 'Active', calendar: 'Check' },
    { id: 2, taName: 'Jane Smith', username: 'janesmith', availability: 'On Leave', calendar: 'Check' },
    { id: 3, taName: 'Mike Johnson', username: 'mikejohnson', availability: 'Inactive', calendar: 'Check' },
    { id: 4, taName: 'Emily Davis', username: 'emilydavis', availability: 'Active', calendar: 'Check' },
    { id: 5, taName: 'Chris Lee', username: 'chrislee', availability: 'On Leave', calendar: 'Check' },
    { id: 6, taName: 'Anna White', username: 'annawhite', availability: 'Inactive', calendar: 'Check' },
    { id: 7, taName: 'James Brown', username: 'jamesbrown', availability: 'Active', calendar: 'Check' },
    { id: 8, taName: 'Linda Black', username: 'lindablack', availability: 'On Leave', calendar: 'Check' },
    { id: 9, taName: 'Michael Green', username: 'michaelgreen', availability: 'Inactive', calendar: 'Check' },
    { id: 10, taName: 'Susan Blue', username: 'susanblue', availability: 'Active', calendar: 'Check' },
    { id: 11, taName: 'Robert Red', username: 'robertred', availability: 'On Leave', calendar: 'Check' },
    { id: 12, taName: 'Patricia Yellow', username: 'patriciayellow', availability: 'Inactive', calendar: 'Check' },
    { id: 13, taName: 'Charles Purple', username: 'charlespurple', availability: 'Active', calendar: 'Check' },
    { id: 14, taName: 'Barbara Pink', username: 'barbarapink', availability: 'On Leave', calendar: 'Check' },
    { id: 15, taName: 'Joseph Orange', username: 'josephorange', availability: 'Inactive', calendar: 'Check' },
    { id: 16, taName: 'Jessica Violet', username: 'jessicaviolet', availability: 'Active', calendar: 'Check' },
    { id: 17, taName: 'Thomas Brown', username: 'thomasbrown', availability: 'On Leave', calendar: 'Check' },
    { id: 18, taName: 'Sarah Grey', username: 'sarahgrey', availability: 'Inactive', calendar: 'Check' },
    { id: 19, taName: 'Daniel White', username: 'danielwhite', availability: 'Active', calendar: 'Check' },
    { id: 20, taName: 'Nancy Black', username: 'nancyblack', availability: 'On Leave', calendar: 'Check' },
    { id: 21, taName: 'Paul Green', username: 'paulgreen', availability: 'Inactive', calendar: 'Check' },
    { id: 22, taName: 'Lisa Blue', username: 'lisablue', availability: 'Active', calendar: 'Check' },
    { id: 23, taName: 'Mark Red', username: 'markred', availability: 'On Leave', calendar: 'Check' },
    { id: 24, taName: 'Sandra Yellow', username: 'sandrayellow', availability: 'Inactive', calendar: 'Check' },
    { id: 25, taName: 'Steven Purple', username: 'stevenpurple', availability: 'Active', calendar: 'Check' },
];
