export const AssignedStudentData = [
    { id: 1, studentName: 'John Doe', academicTerm: 'Fall 2021', batch: 'A1',  isActive: true },
    { id: 2, studentName: 'Jane Smith', academicTerm: 'Spring 2021', batch: 'B1',  isActive: true },
    { id: 3, studentName: 'Mike Johnson', academicTerm: 'Winter 2021', batch: 'C1',  isActive: true },
    { id: 4, studentName: 'Emily Brown', academicTerm: 'Fall 2021', batch: 'A2',  isActive: true },
    { id: 5, studentName: 'Alice Johnson', academicTerm: 'Spring 2022', batch: 'B2',  isActive: true },
    { id: 6, studentName: 'Bob Davis', academicTerm: 'Winter 2022', batch: 'C2',  isActive: true },
    { id: 7, studentName: 'Carol Wilson', academicTerm: 'Fall 2022', batch: 'A3',  isActive: true },
    { id: 8, studentName: 'David Harris', academicTerm: 'Spring 2022', batch: 'B3',  isActive: true },
    { id: 9, studentName: 'Eve Clark', academicTerm: 'Winter 2022', batch: 'C3',  isActive: true },
    { id: 10, studentName: 'Frank Lewis', academicTerm: 'Fall 2023', batch: 'A4',  isActive: true },
    { id: 11, studentName: 'Grace Lee', academicTerm: 'Spring 2023', batch: 'B4',  isActive: true },
    { id: 12, studentName: 'Hank Young', academicTerm: 'Winter 2023', batch: 'C4',  isActive: true },
    { id: 13, studentName: 'Ivy Hall', academicTerm: 'Fall 2023', batch: 'A5',  isActive: true },
    { id: 14, studentName: 'Jack King', academicTerm: 'Spring 2023', batch: 'B5',  isActive: true },
    { id: 15, studentName: 'Kim Lopez', academicTerm: 'Winter 2023', batch: 'C5',  isActive: true },
    { id: 16, studentName: 'Liam Adams', academicTerm: 'Fall 2024', batch: 'A6',  isActive: true },
    { id: 17, studentName: 'Mia Baker', academicTerm: 'Spring 2024', batch: 'B6',  isActive: true },
    { id: 18, studentName: 'Noah Scott', academicTerm: 'Winter 2024', batch: 'C6',  isActive: true },
    { id: 19, studentName: 'Olivia Carter', academicTerm: 'Fall 2024', batch: 'A7',  isActive: true },
    { id: 20, studentName: 'Paul Evans', academicTerm: 'Spring 2024', batch: 'B7',  isActive: true },
    { id: 21, studentName: 'Quinn Turner', academicTerm: 'Winter 2024', batch: 'C7' , isActive: false},
    { id: 22, studentName: 'Rachel Perez', academicTerm: 'Fall 2025', batch: 'A8' , isActive: false},
    { id: 23, studentName: 'Sam Wright', academicTerm: 'Spring 2025', batch: 'B8' , isActive: false},
    { id: 24, studentName: 'Tina Martinez', academicTerm: 'Winter 2025', batch: 'C8' , isActive: false},
    { id: 25, studentName: 'Uma Sanchez', academicTerm: 'Fall 2025', batch: 'A9' , isActive: false},
    { id: 26, studentName: 'Victor Morgan', academicTerm: 'Spring 2025', batch: 'B9' , isActive: false},
    { id: 27, studentName: 'Wendy Brooks', academicTerm: 'Winter 2025', batch: 'C9', isActive: false },
    { id: 28, studentName: 'Xander Bennett', academicTerm: 'Fall 2026', batch: 'A10' , isActive: false},
    { id: 29, studentName: 'Yara Bell', academicTerm: 'Spring 2026', batch: 'B10' , isActive: false},
    { id: 30, studentName: 'Zane Foster', academicTerm: 'Winter 2026', batch: 'C10' , isActive: false},
  ];
  