export const mockManageAvailable = [
    { id: 1, coachName: 'John Doe', username: 'johndoe', location: 'New York', timeZone: 'EST' },
    { id: 2, coachName: 'Jane Smith', username: 'janesmith', location: 'Los Angeles', timeZone: 'PST' },
    { id: 3, coachName: 'Mike Johnson', username: 'mikejohnson', location: 'Chicago', timeZone: 'CST' },
    { id: 4, coachName: 'Emily Brown', username: 'emilybrown', location: 'Houston', timeZone: 'CST' },
    { id: 5, coachName: 'David Lee', username: 'davidlee', location: 'Miami', timeZone: 'EST' },
    { id: 6, coachName: 'Sarah Wilson', username: 'sarahwilson', location: 'San Francisco', timeZone: 'PST' },
    { id: 7, coachName: 'Chris Taylor', username: 'christaylor', location: 'Dallas', timeZone: 'CST' },
    { id: 8, coachName: 'Amanda Martinez', username: 'amandamartinez', location: 'Atlanta', timeZone: 'EST' },
    { id: 9, coachName: 'Daniel Clark', username: 'danielclark', location: 'Seattle', timeZone: 'PST' },
    { id: 10, coachName: 'Kelly White', username: 'kellywhite', location: 'Boston', timeZone: 'EST' },
    { id: 11, coachName: 'Mark Taylor', username: 'marktaylor', location: 'Denver', timeZone: 'MST' },
    { id: 12, coachName: 'Linda Rodriguez', username: 'lindarodriguez', location: 'Philadelphia', timeZone: 'EST' },
    { id: 13, coachName: 'Jason Harris', username: 'jasonharris', location: 'Phoenix', timeZone: 'MST' },
    { id: 14, coachName: 'Michelle King', username: 'michelleking', location: 'Las Vegas', timeZone: 'PST' },
    { id: 15, coachName: 'Ryan Nguyen', username: 'ryannguyen', location: 'Orlando', timeZone: 'EST' },
    { id: 16, coachName: 'Stephanie Scott', username: 'stephaniescott', location: 'San Diego', timeZone: 'PST' },
    { id: 17, coachName: 'Patrick Hill', username: 'patrickhill', location: 'Minneapolis', timeZone: 'CST' },
    { id: 18, coachName: 'Catherine Evans', username: 'catherineevans', location: 'Portland', timeZone: 'PST' },
    { id: 19, coachName: 'Justin Cook', username: 'justincook', location: 'Detroit', timeZone: 'EST' },
    { id: 20, coachName: 'Samantha Morris', username: 'samanthamorris', location: 'Tampa', timeZone: 'EST' },
    { id: 21, coachName: 'Erica Baker', username: 'ericabaker', location: 'Salt Lake City', timeZone: 'MST' },
    { id: 22, coachName: 'Gregory Rivera', username: 'gregoryrivera', location: 'Charlotte', timeZone: 'EST' },
    { id: 23, coachName: 'Melissa Turner', username: 'melissaturner', location: 'Indianapolis', timeZone: 'EST' },
    { id: 24, coachName: 'Brandon Baker', username: 'brandonbaker', location: 'Kansas City', timeZone: 'CST' },
    { id: 25, coachName: 'Christina Wright', username: 'christinawright', location: 'Austin', timeZone: 'CST' },
    { id: 26, coachName: 'Derek Hall', username: 'derekhall', location: 'Raleigh', timeZone: 'EST' },
    { id: 27, coachName: 'Katherine Scott', username: 'katherinescott', location: 'Nashville', timeZone: 'CST' },
    { id: 28, coachName: 'Nicholas Young', username: 'nicholasyoung', location: 'San Antonio', timeZone: 'CST' },
    { id: 29, coachName: 'Monica Hill', username: 'monicahill', location: 'Louisville', timeZone: 'EST' },
    { id: 30, coachName: 'Timothy Roberts', username: 'timothyroberts', location: 'Oklahoma City', timeZone: 'CST' }
];
