export const mockManageAvailable = [
    { id: 1, taName: 'John Doe', username: 'johndoe', location: 'New York', timeZone: 'EST', isActive: true},
    { id: 2, taName: 'Jane Smith', username: 'janesmith', location: 'Los Angeles', timeZone: 'PST', isActive: true },
    { id: 3, taName: 'Mike Johnson', username: 'mikejohnson', location: 'Chicago', timeZone: 'CST' , isActive: true},
    { id: 4, taName: 'Emily Brown', username: 'emilybrown', location: 'Houston', timeZone: 'CST' , isActive: true},
    { id: 5, taName: 'David Lee', username: 'davidlee', location: 'Miami', timeZone: 'EST' , isActive: true},
    { id: 6, taName: 'Sarah Wilson', username: 'sarahwilson', location: 'San Francisco', timeZone: 'PST' , isActive: true},
    { id: 7, taName: 'Chris Taylor', username: 'christaylor', location: 'Dallas', timeZone: 'CST' , isActive: true},
    { id: 8, taName: 'Amanda Martinez', username: 'amandamartinez', location: 'Atlanta', timeZone: 'EST' , isActive: true},
    { id: 9, taName: 'Daniel Clark', username: 'danielclark', location: 'Seattle', timeZone: 'PST' , isActive: true},
    { id: 10, taName: 'Kelly White', username: 'kellywhite', location: 'Boston', timeZone: 'EST' , isActive: true},
    { id: 11, taName: 'Mark Taylor', username: 'marktaylor', location: 'Denver', timeZone: 'MST' , isActive: true},
    { id: 12, taName: 'Linda Rodriguez', username: 'lindarodriguez', location: 'Philadelphia', timeZone: 'EST' , isActive: true},
    { id: 13, taName: 'Jason Harris', username: 'jasonharris', location: 'Phoenix', timeZone: 'MST' , isActive: true},
    { id: 14, taName: 'Michelle King', username: 'michelleking', location: 'Las Vegas', timeZone: 'PST' , isActive: true},
    { id: 15, taName: 'Ryan Nguyen', username: 'ryannguyen', location: 'Orlando', timeZone: 'EST' , isActive: true},
    { id: 16, taName: 'Stephanie Scott', username: 'stephaniescott', location: 'San Diego', timeZone: 'PST' , isActive: true},
    { id: 17, taName: 'Patrick Hill', username: 'patrickhill', location: 'Minneapolis', timeZone: 'CST' , isActive: true},
    { id: 18, taName: 'Catherine Evans', username: 'catherineevans', location: 'Portland', timeZone: 'PST' , isActive: true},
    { id: 19, taName: 'Justin Cook', username: 'justincook', location: 'Detroit', timeZone: 'EST' , isActive: true},
    { id: 20, taName: 'Samantha Morris', username: 'samanthamorris', location: 'Tampa', timeZone: 'EST' , isActive: true},
    { id: 21, taName: 'Erica Baker', username: 'ericabaker', location: 'Salt Lake City', timeZone: 'MST' , isActive: true},
    { id: 22, taName: 'Gregory Rivera', username: 'gregoryrivera', location: 'Charlotte', timeZone: 'EST' , isActive: true},
    { id: 23, taName: 'Melissa Turner', username: 'melissaturner', location: 'Indianapolis', timeZone: 'EST' , isActive: true},
    { id: 24, taName: 'Brandon Baker', username: 'brandonbaker', location: 'Kansas City', timeZone: 'CST' , isActive: true},
    { id: 25, taName: 'Christina Wright', username: 'christinawright', location: 'Austin', timeZone: 'CST' , isActive: true},
    { id: 26, taName: 'Derek Hall', username: 'derekhall', location: 'Raleigh', timeZone: 'EST' , isActive: true},
    { id: 27, taName: 'Katherine Scott', username: 'katherinescott', location: 'Nashville', timeZone: 'CST' , isActive: true},
    { id: 28, taName: 'Nicholas Young', username: 'nicholasyoung', location: 'San Antonio', timeZone: 'CST' , isActive: true},
    { id: 29, taName: 'Monica Hill', username: 'monicahill', location: 'Louisville', timeZone: 'EST' , isActive: true},
    { id: 30, taName: 'Timothy Roberts', username: 'timothyroberts', location: 'Oklahoma City', timeZone: 'CST',isActive: true }
];
