export const studentsFakeData = [
    {
        id: 34,
        name: "example",
        user_id: "8",
        email: "example@example.com",
        class_id: 2,
        board_id: 2,
        stream_id: 2,
        phone: "7777777777",
        primary_phone: null,
        primary_email: null,
        is_active: 1,
        created_at: "2024-06-01T10:20:30.000000Z",
        packages : [
            {
                id: 4,
                serial_number: null,
                name : "Associate of Science in AI: Data Analyst",
                product_id: 3,
                PSIS_Key: "2",
                start_date: "2024-11-10",
                end_date: "2025-11-10",
                duration: "365",
                cost: 5000,
                tax: 5,
                cost_2: 5000,
                tax_2: 5,
                cost_3: null,
                tax_3: null,
                total_price: 10010,
                description: "Description",
                is_active: 1,
                created_by_id: 2,
                created_by_type: "admin",
                deleted_at: null,
                created_at: "2024-06-01T09:15:00.000000Z",
                updated_at: "2024-06-05T13:25:45.000000Z",
                product: {
                    id: 3,
                    name: "Associate Degree in Data Science",
                    PSIS_Product_Key: "0003",
                    product_category_id: 4,
                    is_active: 1,
                    created_by_id: 2,
                    created_by_type: "admin",
                    deleted_at: null,
                    created_at: "2024-05-28T08:20:50.000000Z",
                    updated_at: "2024-06-01T11:03:56.000000Z"
                }
            },
        ]
    },
    {
        id: 34,
        name: "example",
        user_id: "8",
        email: "example@example.com",
        class_id: 2,
        board_id: 2,
        stream_id: 2,
        phone: "7777777777",
        primary_phone: null,
        primary_email: null,
        is_active: 1,
        created_at: "2024-06-01T10:20:30.000000Z",
        packages: [
            {
                id: 4,
                serial_number: null,
                name: "Associate of Science in AI: Data Analyst",
                product_id: 3,
                PSIS_Key: "2",
                start_date: "2024-11-10",
                end_date: "2025-11-10",
                duration: "365",
                cost: 5000,
                tax: 5,
                cost_2: 5000,
                tax_2: 5,
                cost_3: null,
                tax_3: null,
                total_price: 10010,
                description: "Description",
                is_active: 1,
                created_by_id: 2,
                created_by_type: "admin",
                deleted_at: null,
                created_at: "2024-06-01T09:15:00.000000Z",
                updated_at: "2024-06-05T13:25:45.000000Z",
                product: {
                    id: 3,
                    name: "Associate Degree in Data Science",
                    PSIS_Product_Key: "0003",
                    product_category_id: 4,
                    is_active: 1,
                    created_by_id: 2,
                    created_by_type: "admin",
                    deleted_at: null,
                    created_at: "2024-05-28T08:20:50.000000Z",
                    updated_at: "2024-06-01T11:03:56.000000Z"
                }
            },
        ]
    },
    {
        id: 34,
        name: "example",
        user_id: "8",
        email: "example@example.com",
        class_id: 2,
        board_id: 2,
        stream_id: 2,
        phone: "7777777777",
        primary_phone: null,
        primary_email: null,
        is_active: 1,
        created_at: "2024-06-01T10:20:30.000000Z",
        packages: [
            {
                id: 4,
                serial_number: null,
                name: "Associate of Science in AI: Data Analyst",
                product_id: 3,
                PSIS_Key: "2",
                start_date: "2024-11-10",
                end_date: "2025-11-10",
                duration: "365",
                cost: 5000,
                tax: 5,
                cost_2: 5000,
                tax_2: 5,
                cost_3: null,
                tax_3: null,
                total_price: 10010,
                description: "Description",
                is_active: 1,
                created_by_id: 2,
                created_by_type: "admin",
                deleted_at: null,
                created_at: "2024-06-01T09:15:00.000000Z",
                updated_at: "2024-06-05T13:25:45.000000Z",
                product: {
                    id: 3,
                    name: "Associate Degree in Data Science",
                    PSIS_Product_Key: "0003",
                    product_category_id: 4,
                    is_active: 1,
                    created_by_id: 2,
                    created_by_type: "admin",
                    deleted_at: null,
                    created_at: "2024-05-28T08:20:50.000000Z",
                    updated_at: "2024-06-01T11:03:56.000000Z"
                }
            }
        ]
    },
]
