export const studentDummyDatadata = [
    {
        "id": 12,
        "name": "test",
        "user_id": "4",
        "email": "test@gmail.com",
        "class_id": 1,
        "board_id": 1,
        "stream_id": 1,
        "phone": "8888888888",
        "primary_phone": null,
        "primary_email": null,
        "is_active": 1,
        "created_at": "2024-05-28T09:48:17.000000Z",
        "packages": [
            {
                "id": 3,
                "serial_number": null,
                "name": "Associate of Science in AI: Jr. Data Scientist",
                "product_id": 2,
                "PSIS_Key": "1",
                "start_date": "2024-12-12",
                "end_date": "2025-12-12",
                "duration": "567",
                "cost": 1,
                "tax": 1,
                "cost_2": 1,
                "tax_2": 1,
                "cost_3": null,
                "tax_3": null,
                "total_price": 2.02,
                "description": " Description",
                "is_active": 1,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-28T09:32:50.000000Z",
                "updated_at": "2024-05-31T12:06:08.000000Z",
                "product": {
                    "id": 2,
                    "name": "Associate Degree in AI",
                    "PSIS_Product_Key": "0001",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-28T06:31:20.000000Z",
                    "updated_at": "2024-05-31T12:03:56.000000Z"
                }
            },
            {
                "id": 1,
                "serial_number": null,
                "name": "Associate of Science in AI: AI/ML Engineer",
                "product_id": 1,
                "PSIS_Key": null,
                "start_date": "2024-08-30",
                "end_date": null,
                "duration": "24 Months",
                "cost": 10000,
                "tax": 12,
                "cost_2": 12000,
                "tax_2": 12,
                "cost_3": null,
                "tax_3": null,
                "total_price": 24640,
                "description": "Description",
                "is_active": 0,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-27T07:04:53.000000Z",
                "updated_at": "2024-06-03T12:19:13.000000Z",
                "product": {
                    "id": 1,
                    "name": "Bachelors Degree in AI",
                    "PSIS_Product_Key": "0002",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-22T12:59:50.000000Z",
                    "updated_at": "2024-05-31T12:04:16.000000Z"
                }
            }
        ]
    },
    {
        "id": 11,
        "name": "Ankul",
        "user_id": "2",
        "email": "ankul@gmail.com",
        "class_id": 1,
        "board_id": 1,
        "stream_id": 1,
        "phone": "999999999",
        "primary_phone": null,
        "primary_email": null,
        "is_active": 1,
        "created_at": "2024-05-28T09:35:22.000000Z",
        "packages": [
            {
                "id": 3,
                "serial_number": null,
                "name": "Associate of Science in AI: Jr. Data Scientist",
                "product_id": 2,
                "PSIS_Key": "1",
                "start_date": "2024-12-12",
                "end_date": "2025-12-12",
                "duration": "567",
                "cost": 1,
                "tax": 1,
                "cost_2": 1,
                "tax_2": 1,
                "cost_3": null,
                "tax_3": null,
                "total_price": 2.02,
                "description": "Description",
                "is_active": 1,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-28T09:32:50.000000Z",
                "updated_at": "2024-05-31T12:06:08.000000Z",
                "product": {
                    "id": 2,
                    "name": "Associate Degree in AI",
                    "PSIS_Product_Key": "0001",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-28T06:31:20.000000Z",
                    "updated_at": "2024-05-31T12:03:56.000000Z"
                }
            },
            {
                "id": 1,
                "serial_number": null,
                "name": "Associate of Science in AI: AI/ML Engineer",
                "product_id": 1,
                "PSIS_Key": null,
                "start_date": "2024-08-30",
                "end_date": null,
                "duration": "24 Months",
                "cost": 10000,
                "tax": 12,
                "cost_2": 12000,
                "tax_2": 12,
                "cost_3": null,
                "tax_3": null,
                "total_price": 24640,
                "description": "Description",
                "is_active": 0,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-27T07:04:53.000000Z",
                "updated_at": "2024-06-03T12:19:13.000000Z",
                "product": {
                    "id": 1,
                    "name": "Bachelors Degree in AI",
                    "PSIS_Product_Key": "0002",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-22T12:59:50.000000Z",
                    "updated_at": "2024-05-31T12:04:16.000000Z"
                }
            }
        ]
    },
    {
        "id": 5,
        "name": "Parul",
        "user_id": "12345",
        "email": "parul.s@sarasai.org",
        "class_id": 1,
        "board_id": 1,
        "stream_id": 1,
        "phone": "6666668880",
        "primary_phone": null,
        "primary_email": null,
        "is_active": 1,
        "created_at": "2024-05-27T11:10:34.000000Z",
        "packages": [
            {
                "id": 1,
                "serial_number": null,
                "name": "Associate of Science in AI: AI/ML Engineer",
                "product_id": 1,
                "PSIS_Key": null,
                "start_date": "2024-08-30",
                "end_date": null,
                "duration": "24 Months",
                "cost": 10000,
                "tax": 12,
                "cost_2": 12000,
                "tax_2": 12,
                "cost_3": null,
                "tax_3": null,
                "total_price": 24640,
                "description": "Description",
                "is_active": 0,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-27T07:04:53.000000Z",
                "updated_at": "2024-06-03T12:19:13.000000Z",
                "product": {
                    "id": 1,
                    "name": "Bachelors Degree in AI",
                    "PSIS_Product_Key": "0002",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-22T12:59:50.000000Z",
                    "updated_at": "2024-05-31T12:04:16.000000Z"
                }
            }
        ]
    },
    {
        "id": 4,
        "name": "Jitesh Shivgan",
        "user_id": "1",
        "email": "jitesh.s@sarasai.com",
        "class_id": 1,
        "board_id": 1,
        "stream_id": 1,
        "phone": "8440093177",
        "primary_phone": "8440093177",
        "primary_email": "jitesh.s@sarasai.com",
        "is_active": 1,
        "created_at": "2024-05-27T07:09:50.000000Z",
        "packages": [
            {
                "id": 1,
                "serial_number": null,
                "name": "Associate of Science in AI: AI/ML Engineer",
                "product_id": 1,
                "PSIS_Key": null,
                "start_date": "2024-08-30",
                "end_date": null,
                "duration": "24 Months",
                "cost": 10000,
                "tax": 12,
                "cost_2": 12000,
                "tax_2": 12,
                "cost_3": null,
                "tax_3": null,
                "total_price": 24640,
                "description": "Description",
                "is_active": 0,
                "created_by_id": 1,
                "created_by_type": "admin",
                "deleted_at": null,
                "created_at": "2024-05-27T07:04:53.000000Z",
                "updated_at": "2024-06-03T12:19:13.000000Z",
                "product": {
                    "id": 1,
                    "name": "Bachelors Degree in AI",
                    "PSIS_Product_Key": "0002",
                    "product_category_id": 3,
                    "is_active": 1,
                    "created_by_id": 1,
                    "created_by_type": "admin",
                    "deleted_at": null,
                    "created_at": "2024-05-22T12:59:50.000000Z",
                    "updated_at": "2024-05-31T12:04:16.000000Z"
                }
            }
        ]
    }
]
