name: Build and Deploy Frontend

on:
  push:
    branches:
      - Developer  # Trigger only on the 'developer' branch
  schedule:
    - cron: '30 9 * * 3'  # Every Wednesday at 3:00 PM IST
    - cron: '30 9 * * 5'  # Every Friday at 3:00 PM IST

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          npm install
        working-directory: SARAS_AI_FRONTEND

      - name: Build frontend project
        run: npm run build
        working-directory: SARAS_AI_FRONTEND

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure Docker Login
      - name: Azure Docker Login
        if: success()
        uses: azure/docker-login@v1
        with:
          login-server: sarasai.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build Docker image for frontend
      - name: Build Docker image for frontend
        if: success()
        run: |
          cd SARAS_AI_FRONTEND
          docker build -t sarasai.azurecr.io/sarasfront1:${{ github.sha }} .

      # Tag Docker image as 'latest'
      - name: Tag Docker image as 'latest'
        if: success()
        run: |
          docker tag sarasai.azurecr.io/sarasfront1:${{ github.sha }} sarasai.azurecr.io/sarasfront1:latest

      # Push Docker image with commit SHA tag to ACR
      - name: Push Docker image with commit SHA tag to ACR
        if: success()
        run: |
          docker push sarasai.azurecr.io/sarasfront1:${{ github.sha }}

      # Push Docker image with 'latest' tag to ACR
      - name: Push Docker image with 'latest' tag to ACR
        if: success()
        run: |
          docker push sarasai.azurecr.io/sarasfront1:latest

          
      - name: Deploy to Azure Container Apps
        if: success()
        run: |
         RESOURCE_GROUP=devops-testing-rg
         CONTAINER_APP_NAME=sarasaifrontend
         ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
         IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/sarasaifrontend

          for i in {1..5}; do
            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} && break || sleep 60
          done
